### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by shoh1125** [shoh1125/first_app#1]
# URL
https://furima-38588.onrender.com/
# Basic認証のIDとパスワード
id:admin  
pass:2222
# 出品者用のメールアドレスとパスワード
ユーザー①
mail:test1@test.com
password:testtest1
# 購入者用のメールアドレスとパスワード
ユーザー②
mail:test2@test.com
password:testtest2

**Comment by shodai-ito** [comment]
@shoh1125 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`商品詳細機能`**
- [x]  **商品出品時に登録した情報（商品名・商品画像・販売価格・配送料負担・商品説明・出品者名・カテゴリー・商品の状態・発送元の地域・発送日の目安）が、見本アプリと同様の形で出力されること**
商品説明の項目が正しく表示されていないかと存じます。
出品時に入力した商品説明が表示されるようにしましょう。
<img width="914" alt="スクリーンショット 2023-03-23 9 38 05" src="https://user-images.githubusercontent.com/62537107/227069769-8973b68c-d707-443b-afda-3107956e26f9.png">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by shoh1125** [comment]
<img width="1272" alt="39610f8b22b63f6c70e65203134d4b81" src="https://user-images.githubusercontent.com/118186430/227095793-732d4964-c5f2-4414-8676-02f12e34bb17.png">

**Comment by motomuun** [comment]
@shoh1125 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

`本メッセージ内で、今後の学習についてご案内しています。必ず確認するようにしてください。`

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

------------------------------------------------------------------------------------------
◆ 今後の流れについてのご案内（※詳細は下記リンクのガイダンス資料参照）
------------------------------------------------------------------------------------------
◎この後の期間では、以下のアクションが必要となります。
・最終課題説明文の作成・提出
・FURIMAへの追加機能の実装 または オリジナルアプリ開発
・上記の開発に関する要件定義書の提出
・履歴書と職務経歴書の作成・提出（転職サポートありの方）
・学習成果発表会の準備

◎下記リンク先の「**追加実装・オリジナルアプリ開発 ガイダンス資料**」を必ずご確認ください。
**https://master.tech-camp.in/v2/curriculums/7839**

------------------------------------------------------------------------------------------
◆ さいごに
------------------------------------------------------------------------------------------
◎ガイダンス資料を確認した上で、今後の流れについて不明点がございましたら、担当ライフコーチまでご相談ください。

◎いよいよ卒業までのラストスパートです。これまで頑張ってきたことをフル活用して、最大限の受講成果につなげていきましょう。

![lgtm_01](https://user-images.githubusercontent.com/65059944/227096978-dec6eae7-ea7f-4eeb-adc8-35dc7ff47659.png)
